name: Generate DNS filtering files

on:
  schedule:
    # runs every day
    - cron: "0 0 * * *"

jobs:
  weekly:
    name: Convert hosts files to RPZ files
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: main

      - run: |
          ./make
          git config --local user.name "Frans Allen"
          git config --local user.email "fransallen@users.noreply.github.com"
          git add .
          git commit -m "chore: daily routines"
          git push
